[Icon Theme]
Name=Crail Paper
Comment=A custom icon theme inspired by modern design principles.
Inherits=cosmic,pop,hicolor
Directories=apps/scalable,places/scalable,mimetypes/scalable

[apps/scalable]
Size=128
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[places/scalable]
Size=128
Context=Places
Type=Scalable
MinSize=16
MaxSize=512

[mimetypes/scalable]
Size=128
Context=MimeTypes
Type=Scalable
MinSize=16
MaxSize=512
